### ISSUE TITLE
[FEATURE]: Currently selected should be of different color

### ISSUE THREAD

**Issue by bottercode** [btw-so/btw#5]
https://user-images.githubusercontent.com/74648201/235743245-55767090-adce-4966-8549-36799495351b.mp4

for example:
if currently B(Bold) is selected it should be of different color

**Comment by bottercode** [comment]
@jalotra Hovering is fine. It's just a feature update to change the color of the button currently selected.
eg. While you are typing with B (Bold) selected, it should be of different color

**Comment by siddug** [comment]
@bottercode Thanks for pointing it out. Fixed. Live now.
